#ifndef INCLUDES_H
#define INCLUDES_H
#endif // INCLUDES_H
#include <QNetworkInterface>
#include "mainwindow.h"
#include <QCoreApplication>
#include <QThread>
#include <QTimer>
#include <QMessageBox>
#include "ui_mainwindow.h"
#include <QRegularExpression>
#include <tlhelp32.h>
#include <windows.h>
#include <pdh.h>
#include <iphlpapi.h>
#include <netioapi.h>
#include <iostream>
#include <string>
#include <QDateTime>
#include <QProcess>
#include <QOpenGLContext>
#include <QOpenGLFunctions>
#include <QOffscreenSurface>
#include <QDebug>
#include <QBuffer>
#include <vector>
#include <cstdlib>
#include <cstring>
#include <wbemidl.h>
#include <comdef.h>
