name: Build HWTracker

on:
  push:
    branches: [ main, master ]
    # Aşağıdaki dosyalar değiştiğinde Build işlemini tetikleme
    paths-ignore:
      - '**.md'
      - 'assets/**'
      - 'LICENSE'
      - '.gitignore'
      - 'docs/**'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '**.md'
      - 'assets/**'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        # Temel modüller (Network, Widgets) varsayılan olarak gelir.
    
    - name: Configure CMake
      run: |
        cmake -B build -S . -DCMAKE_PREFIX_PATH=${{ env.Qt6_DIR }} -DCMAKE_BUILD_TYPE=Release
    
    - name: Build
      run: |
        cmake --build build --config Release
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: HWTracker-Windows-Package
        # HwTracker.exe'nin büyük/küçük harf uyumuna ve yoluna dikkat et
        path: build/Release/HwTracker.exe
